version: '3.8'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - INITIAL_PROMPT_FILE_PATH=${INITIAL_PROMPT_FILE_PATH}
      - HUGGINGFACE_AUTH_TOKEN=${HUGGINGFACE_AUTH_TOKEN}
      # Set other environment variables as needed